<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('exercise_equipment', function (Blueprint $table) {
            $table->id();
            $table->uuid('uuid')->unique();
            $table->string('code')->unique();
            $table->string('name')->unique();   // barra, mancuerna, banda, TRX, etc.
            $table->boolean('is_machine')->default(false);
            $table->enum('status', ['draft', 'published', 'archived'])->default('draft');
            $table->text('description')->nullable();
            $table->integer('order')->default(0);
            $table->json('meta')->nullable();
            $table->timestamps();
        });
/*
        // Seed: exercise_equipment
        $now = now();
        DB::table('exercise_equipment')->insert([
            [
                'uuid' => (string) Str::orderedUuid(),
                'name' => 'Peso corporal',
                'code' => 'bodyweight',
                'is_machine' => false,
                'description' => 'Ejercicios sin implementos.',
                'order' => 1,
                'status' => 'published',
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => (string) Str::orderedUuid(),
                'name' => 'Barra',
                'code' => 'barbell',
                'is_machine' => false,
                'description' => 'Barra olímpica/estándar.',
                'order' => 2,
                'status' => 'published',
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => (string) Str::orderedUuid(),
                'name' => 'Mancuerna',
                'code' => 'dumbbell',
                'is_machine' => false,
                'description' => 'Par o mancuerna individual.',
                'order' => 3,
                'status' => 'published',
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => (string) Str::orderedUuid(),
                'name' => 'Kettlebell',
                'code' => 'kettlebell',
                'is_machine' => false,
                'description' => 'Pesa rusa.',
                'order' => 4,
                'status' => 'published',
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => (string) Str::orderedUuid(),
                'name' => 'Barra EZ',
                'code' => 'ez_bar',
                'is_machine' => false,
                'description' => 'Barra curvada para curl y extensiones.',
                'order' => 5,
                'status' => 'published',
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => (string) Str::orderedUuid(),
                'name' => 'Barra hexagonal',
                'code' => 'trap_bar',
                'is_machine' => false,
                'description' => 'Hex bar / trap bar.',
                'order' => 6,
                'status' => 'published',
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Máquinas / poleas
            [
                'uuid' => (string) Str::orderedUuid(),
                'name' => 'Máquina de poleas',
                'code' => 'cable_machine',
                'is_machine' => true,
                'description' => 'Estación de poleas ajustables.',
                'order' => 10,
                'status' => 'published',
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => (string) Str::orderedUuid(),
                'name' => 'Máquina guiada (Smith)',
                'code' => 'smith_machine',
                'is_machine' => true,
                'description' => 'Barra guiada en rieles.',
                'order' => 11,
                'status' => 'published',
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => (string) Str::orderedUuid(),
                'name' => 'Máquina de placas',
                'code' => 'plate_loaded_machine',
                'is_machine' => true,
                'description' => 'Máquina cargada con discos.',
                'order' => 12,
                'status' => 'published',
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => (string) Str::orderedUuid(),
                'name' => 'Prensa de piernas',
                'code' => 'leg_press_machine',
                'is_machine' => true,
                'description' => 'Leg press horizontal/45°.',
                'order' => 13,
                'status' => 'published',
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => (string) Str::orderedUuid(),
                'name' => 'Extensión de cuádriceps',
                'code' => 'leg_extension_machine',
                'is_machine' => true,
                'description' => 'Máquina de extensión de rodilla.',
                'order' => 14,
                'status' => 'published',
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => (string) Str::orderedUuid(),
                'name' => 'Curl femoral',
                'code' => 'leg_curl_machine',
                'is_machine' => true,
                'description' => 'Máquina de flexión de rodilla.',
                'order' => 15,
                'status' => 'published',
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => (string) Str::orderedUuid(),
                'name' => 'Jalón al pecho',
                'code' => 'lat_pulldown_machine',
                'is_machine' => true,
                'description' => 'Máquina de jalón dorsales.',
                'order' => 16,
                'status' => 'published',
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => (string) Str::orderedUuid(),
                'name' => 'Remo sentado',
                'code' => 'seated_row_machine',
                'is_machine' => true,
                'description' => 'Máquina de remo con cable.',
                'order' => 17,
                'status' => 'published',
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Accesorios y libres
            [
                'uuid' => (string) Str::orderedUuid(),
                'name' => 'Banda elástica',
                'code' => 'resistance_band',
                'is_machine' => false,
                'description' => 'Banda o miniband.',
                'order' => 20,
                'status' => 'published',
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => (string) Str::orderedUuid(),
                'name' => 'TRX / Suspensión',
                'code' => 'suspension_trainer',
                'is_machine' => false,
                'description' => 'Entrenador en suspensión.',
                'order' => 21,
                'status' => 'published',
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => (string) Str::orderedUuid(),
                'name' => 'Banco',
                'code' => 'bench',
                'is_machine' => false,
                'description' => 'Banco plano/inclinado/declinado.',
                'order' => 22,
                'status' => 'published',
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => (string) Str::orderedUuid(),
                'name' => 'Cajón pliométrico',
                'code' => 'plyo_box',
                'is_machine' => false,
                'description' => 'Box/step para saltos y apoyos.',
                'order' => 23,
                'status' => 'published',
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => (string) Str::orderedUuid(),
                'name' => 'Balón medicinal',
                'code' => 'medicine_ball',
                'is_machine' => false,
                'description' => 'Med ball / slam ball.',
                'order' => 24,
                'status' => 'published',
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => (string) Str::orderedUuid(),
                'name' => 'Pelota suiza',
                'code' => 'swiss_ball',
                'is_machine' => false,
                'description' => 'Fitball / estabilidad.',
                'order' => 25,
                'status' => 'published',
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => (string) Str::orderedUuid(),
                'name' => 'Trineo',
                'code' => 'sled',
                'is_machine' => false,
                'description' => 'Sled empuje/arrastre.',
                'order' => 26,
                'status' => 'published',
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => (string) Str::orderedUuid(),
                'name' => 'Landmine',
                'code' => 'landmine',
                'is_machine' => false,
                'description' => 'Pivote para barra.',
                'order' => 27,
                'status' => 'published',
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Cardio
            [
                'uuid' => (string) Str::orderedUuid(),
                'name' => 'Cinta de correr',
                'code' => 'treadmill',
                'is_machine' => true,
                'description' => 'Caminadora / treadmill.',
                'order' => 30,
                'status' => 'published',
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => (string) Str::orderedUuid(),
                'name' => 'Bicicleta',
                'code' => 'exercise_bike',
                'is_machine' => true,
                'description' => 'Spinning/air bike.',
                'order' => 31,
                'status' => 'published',
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => (string) Str::orderedUuid(),
                'name' => 'Rower',
                'code' => 'rower',
                'is_machine' => true,
                'description' => 'Remo ergométrico.',
                'order' => 32,
                'status' => 'published',
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => (string) Str::orderedUuid(),
                'name' => 'Elíptico',
                'code' => 'elliptical',
                'is_machine' => true,
                'description' => 'Máquina elíptica.',
                'order' => 33,
                'status' => 'published',
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Otros útiles
            [
                'uuid' => (string) Str::orderedUuid(),
                'name' => 'Discos',
                'code' => 'weight_plate',
                'is_machine' => false,
                'description' => 'Placas/discos de peso.',
                'order' => 40,
                'status' => 'published',
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => (string) Str::orderedUuid(),
                'name' => 'Saco de arena',
                'code' => 'sandbag',
                'is_machine' => false,
                'description' => 'Sandbag de entrenamiento.',
                'order' => 41,
                'status' => 'published',
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);*/
    }
    public function down(): void
    {
        Schema::dropIfExists('exercise_equipment');
    }
};
